package com.omniquery.core.llm;

import com.omniquery.core.model.GeneratedSql;

import java.util.ArrayList;
import java.util.List;

public class SqlGenerationOutput {

    private String sql;
    private List<String> tables = new ArrayList<>();
    private List<String> columns = new ArrayList<>();
    private String explanation;

    public GeneratedSql toGeneratedSql() {
        if (sql == null || sql.isBlank()) {
            throw new IllegalArgumentException("LLM did not return SQL");
        }
        return new GeneratedSql(sql.trim(), nonNull(tables), nonNull(columns), explanation == null ? "Generated by LangChain4j AiServices" : explanation);
    }

    public String getSql() {
        return sql;
    }

    public void setSql(String sql) {
        this.sql = sql;
    }

    public List<String> getTables() {
        return tables;
    }

    public void setTables(List<String> tables) {
        this.tables = tables;
    }

    public List<String> getColumns() {
        return columns;
    }

    public void setColumns(List<String> columns) {
        this.columns = columns;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    private List<String> nonNull(List<String> values) {
        return values == null ? List.of() : values;
    }
}
